### ISSUE TITLE
Input type date missing initial value or v-model

### ISSUE THREAD

**Issue by coelloj** [Brugarolas/vuersatile-components#1]
Hi, 
i have issue when  use vuersatile in input type date. Add component and not show the params.  
![image](https://user-images.githubusercontent.com/19982668/231641219-f29cc3e8-2ce2-4959-81af-479a251f007f.png)

**Comment by Brugarolas** [comment]
Gracias por tu comentario!

Ya está arreglado en la última versión.

Se usa así:

_____________________

Thanks for your comment!

Just fixed in the last version.

You can use it like this:

```html
<InputDate name="date" label="Select a date" placeholder="Select date" :initialValue="new Date()" />
```

_____________________

PD: Unfortunately, `InputDate` does not support `validations` yet,
